# Generated by Django 4.0.5 on 2023-05-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='association',
            field=models.CharField(choices=[('Particular', 'particular'), ('Convênio', 'convenio')], max_length=20, null=True),
        ),
    ]
