# Generated by Django 4.0.5 on 2023-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_recommendation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='date_limit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='days_limit',
            field=models.IntegerField(verbose_name='Limite de dias'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nome do procedimento'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='association',
            field=models.CharField(choices=[('Particular', 'particular'), ('Convênio', 'convenio')], max_length=20, null=True, verbose_name='Associação'),
        ),
    ]
