# Generated by Django 4.0.5 on 2023-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_procedure_date_limit_alter_procedure_days_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='date_modified_manually',
            field=models.BooleanField(default=False),
        ),
    ]
