# Generated by Django 4.0.5 on 2023-05-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_remove_procedure_date_modified_manually'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='type_procedure',
            field=models.CharField(choices=[('Pre_op', 'Pré-operatório'), ('Pos_op', 'Pós-operatório')], max_length=20, null=True),
        ),
    ]
