# Generated by Django 4.0.5 on 2023-05-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_alter_procedure_type_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='date_limit',
        ),
    ]
