# Generated by Django 4.0.5 on 2023-05-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_remove_procedure_date_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='type_procedure',
        ),
        migrations.AddField(
            model_name='userprocedure',
            name='type_procedure',
            field=models.CharField(choices=[('pre_op', 'Pré-operatório'), ('pos_op', 'Pós-operatório')], max_length=20, null=True),
        ),
    ]
