# Generated by Django 4.0.5 on 2023-06-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_remove_procedure_type_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bariatric',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprocedure',
            name='type_procedure',
            field=models.CharField(choices=[('pre_op', 'Pré-1operatório'), ('pos_op', 'Pós-operatório')], max_length=20, null=True),
        ),
    ]
