# Generated by Django 4.0.5 on 2023-06-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_alter_userprocedure_type_procedure'),
        ('medical', '0011_users_bariatric_alter_userprocedure_type_procedure'),
    ]

    operations = [
    ]
