# Generated by Django 4.0.5 on 2023-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_merge_20230620_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprocedure',
            name='type_procedure',
            field=models.CharField(choices=[('pre_op', 'Pré-operatório'), ('pos_op', 'Pós-operatório')], max_length=20, null=True),
        ),
    ]
