# Generated by Django 4.0.5 on 2023-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_remove_recommendation_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprocedure',
            name='type_procedure',
            field=models.CharField(choices=[('pre_op', 'Pré-1operatório'), ('pos_op', 'Pós-operatório')], default='pre_op', max_length=20, null=True),
        ),
    ]
