# Generated by Django 4.0.5 on 2023-08-16 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0017_alter_userprocedure_type_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprocedure',
            name='type_procedure',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userprocedure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to=settings.AUTH_USER_MODEL),
        ),
    ]
